vtjeng/MIPVerify.jl

REQUIRE
I was having some trouble installing this because it requires the latest versions of JuMP and MathProgBase, while some of my other packages don't yet support those versions. I just verified that the tests work with JuMP 0.17 and MathProgBase 0.6, so I've loosened the required bounds slightly.
=> loosen JuMP and MPB bounds slightly

src/net_components/layers/normalize.jl
Normalize layer mirrors behavior of https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.Normalize, normalizing a tensor image with mean and standard deviation.
=> layers: Add Normalize layer

src/net_components/layers/conv2d.jl, src/net_components/layers/linear.jl
We were previously carrying out simplification of the output of `Conv2d` and `Linear` layers _after_ the entire array of `JuMPAffExpr` had been created. We now do so within the loop, reducing the amount of memory needed.
=> layers: fix memory issue in Conv2d and Linear

src/MIPVerify.jl, src/net_components/core_ops.jl, test/TestHelpers.jl, test/integration/sequential/generated_weights/conv+fc+softmax.jl, test/integration/sequential/generated_weights/mfc+mfc+softmax.jl, test/integration/sequential/trained_weights.jl, test/integration/sequential/trained_weights/MNIST.WK17a_linf0.1_authors.jl, test/integration/sequential/trained_weights/MNIST.n1.jl, test/net_components/core_ops.jl
+ Reorder arguments in `find_adversarial_example`
+ Standardize naming convention for input: `x0` -> `input`
+ Remove unused `tolerance` from `get_vars_for_max_index`
+ Improve test coverage (and fix bug in `maximum_ge` where the method signature was overly restrictive)
=> Slight refactor and improve test coverage.

Project.toml, test/REQUIRE, test/batch_processing_helpers.jl, test/batch_processing_helpers/integration.jl, test/batch_processing_helpers/unit.jl, test/integration.jl, test/integration/sequential.jl, test/integration/sequential/generated_weights.jl, test/integration/sequential/generated_weights/conv+fc+softmax.jl, test/integration/sequential/generated_weights/mfc+mfc+softmax.jl, test/integration/sequential/trained_weights.jl, test/integration/sequential/trained_weights/MNIST.WK17a_linf0.1_authors.jl, test/integration/sequential/trained_weights/MNIST.n1.jl, test/models.jl, test/net_components.jl, test/net_components/core_ops.jl, test/net_components/layers.jl, test/net_components/nets.jl, test/runtests.jl, test/utils.jl, test/utils/import_datasets.jl, test/utils/import_example_nets.jl
+ Reduce amount of time tests take to run by simplifying the conv+fc+softmax.jl test (from generated `8x8` input to generated `6x6` input).
+ Add consistency to test naming: files corresponding to `folders/` including other files, `leaf_files.jl`.
+ Time tests using `TimerOutputs.jl`
=> Reduce amount of time tests take to run

src/net_components/layers/conv2d.jl, test/net_components/layers/conv2d.jl
The top and left pad length computations do not match those of Tensorflow for some use cases. The current implementation assumes that the left and right, and top and bottom pads must be the same, but in some cases they can be different, in which case the left and top pad lengths should be shorter than the right and bottom pads. This can occur when the stride is greater than 1. For example, if the input size is (1, 6, 6, 2), the filter size is (3, 3, 2, 1), and the stride is 2, then the expected output size for SAME padding is (1, 3, 3, 1), which means the top and left pads should be length 0, while the bottom and right pads should be length 1. The existing implementation computes top and left pads of length 1.
This pull request modifies the computation of top and left pad lengths to be …
=> Make SAME padding computation match TensorFlow

src/net_components/layers/skip_unit.jl
In moving from Julia 0.6 to Julia 1.0, addition of vectors to scalars is no longer supported directly with `sum`:
```
julia> x=[1, 2, 3]; y=1; z=2; a=[x, y, z]; sum(a)
ERROR: MethodError: no method matching +(::Array{Int64, 1}, ::Int64)
...
```
This PR provides a quick fix that applies [broadcast addition](https://docs.julialang.org/en/latest/manual/arrays/#Broadcasting-1) via reduce.
I've tested this manually using a ResNet, verifying that we can both forward propagate through the network and set up the relevant optimization problem.
We should add a test that utilizes this `SkipUnit` to prevent future failures.
=> Fix sum usage in skip_unit.

.github/workflows/TagBot.yml
Per a conversation with on julialang.slack.com, we can reduce the frequency of `TagBot` to anything less than three days.
> @vtjeng: By default (https://github.com/JuliaRegistries/TagBot#setup), TagBot runs every hour on my repo. Is this necessary for releases to get tagged immediately, or is it fine if I reduce the frequency with which TagBot runs --- perhaps once every six hours or so? (I am suspecting that this is behind the increased clone traffic to me repository --- I'm having about 24 cloners and 48 clones on my repo after having installed the workflow, but this of course could be someone else). [...] I would be interested if you could point me to something to help me understand how TagBot allows my releases to appear within seconds of the registry PR being merged, too --- that's …
=> Decrease TagBot action frequency to once per day.

src/net_components/layers/conv2d.jl, src/utils/import_weights.jl, test/net_components/layers/conv2d.jl
Using #16 as a starting point, I added support for both valid and fixed padding.
Fixed padding can be passed as `Int64` (same padding for all edges), a tuple of size 2 (y_padding, x_padding) or a tuple of size 4 (top, bottom, left, right).
The implementation follows Tensorflow's conventions, but just to be sure I checked that it matches PyTorch's implementation too.
This is my first time working on MIPVerify, so I might have been a bit overzealous with the unit tests. If that's the case, I'll remove some of them.
Edit: passing -> padding
=> Added valid and fixed padding.

src/net_components/core_ops.jl
**Bugfix**: In `tight_bound`, `getobjectivebound` was empirically observed not to return the correct objective bound when the objective is an affine expression with a constant term (the constant term was ignored). This could lead to correctness issues with the solver where problems that are SAT are incorrectly determined to be UNSAT because (for example) the lower or upper bounds to some ReLU input are too tight.
We believe that this is what is causing the following error message, since expect even LP solves to provide a better answer than interval arithmetic. We will increase the warning message to an error that stops optimization in the future.
```
Tightening via interval_arithmetic gives a better result than lp; using best bound found.
```
A full ticket was [filed …
=> fix tight_bound and maximum_ge

docs/src/tutorials.md, src/MIPVerify.jl, src/batch_processing_helpers.jl, src/models.jl, src/net_components/layers/conv2d.jl, src/net_components/layers/flatten.jl, src/net_components/layers/linear.jl, src/net_components/layers/masked_relu.jl, src/net_components/layers/normalize.jl, src/net_components/layers/pool.jl, src/net_components/layers/relu.jl, src/net_components/layers/skip_unit.jl, src/net_components/layers/zero.jl, src/net_components/nets/sequential.jl, src/net_components/nets/skip_sequential.jl, test/TestHelpers.jl, test/batch_processing_helpers/integration.jl, test/runtests.jl
We no longer really use this, since there is a limited use-case for supporting models that take a very long time to build. (We  work on speeding up the models instead).
=> Deprecate caching of models.

docs/Project.toml, docs/src/net_components/layers.md, docs/src/net_components/nets.md
We were pinning the version of Documenter.jl to `0.23`, which seemed to be causing problems. Upgrading to 0.27 as a quick fix for now.
In addition, we identified some docstrings that were excluded from the docs and add them back in.
=> Re-enable documentation hosting.

.github/workflows/CI.yml, src/MIPVerify.jl, src/net_components/core_ops.jl, test/TestHelpers.jl, test/net_components/core_ops.jl, test/net_components/layers/conv2d.jl, test/net_components/layers/linear.jl, test/net_components/layers/pool.jl, test/runtests.jl
Silence output from solvers 1) for tightening and 2) during all testing via the solution outlined in https://github.com/jump-dev/JuMP.jl/issues/1883#issuecomment-1434120039.
The key function is `optimize_silent!`, which is a wrapper on top of `optimize!`.
```
function optimize_silent!(m)
redirect_stdout(devnull) do
optimize!(m)
Base.Libc.flush_cstdio()
end
end
```
We bump the minimum required Julia version to 1.6 since https://github.com/JuliaLang/julia/pull/36146 (which allows `redirect_stdout(devnull)` to work cross-platform) is only found in 1.6.0 and later. This necessitates dropping `x86` support, since the `HDF5` package (which we use to import data) does not compile in 1.6; see https://github.com/vtjeng/MIPVerify.jl/actions/runs/4201127640/jobs/7287828526#step:6:303.
=> Silence output from solvers for tightening and during testing

Project.toml, src/MIPVerify.jl, src/net_components/core_ops.jl, test/TestHelpers.jl, test/net_components/core_ops.jl, test/net_components/layers/conv2d.jl, test/net_components/layers/linear.jl, test/net_components/layers/pool.jl, test/runtests.jl
Cbc cannot be properly silenced (https://github.com/jump-dev/Cbc.jl/issues/168); using HiGHS avoids the need for the workaround in #131 of using `optimize_silent!`.
Diff excluding #131 for easier comparison: https://github.com/vtjeng/MIPVerify.jl/compare/243ec69...vtjeng/silence-output-w-HiGHS.
This increases test times slightly, but is worth it to avoid the log spam without additional complexity.
=> Switch testing to use HiGHS.jl

Project.toml
With https://github.com/vtjeng/MIPVerify.jl/commit/41b3805a1d7c4c84e1330a1dcb8509e66f1594b1, we should have increased the minimum Julia version to 1.6, since our tests were failing at 1.5 and below. We do so in this PR, and will cut a new `MIPVerify` version ASAP.
(I can't figure out why we needed to bump it to 1.6, but it was clearly necessary for tests to pass. Possibly a JuMP.jl / HiGHS.jl thing?)
=> Bump minimum Julia version to 1.6.

.codecov.yml
We still require that PRs improve overall coverage.
Also, we allow Codecov to comment on our PRs -- that is helpful so we can save a click.
=> Allow PRs that reduce patch coverage.

src/vendor/ConditionalJuMP.jl
This PR is expected to be a no-op.
This is necessary since the `.hi` field appears to be no longer available in `0.22`: https://github.com/vtjeng/MIPVerify.jl/pull/146#issuecomment-1855248801
`inf` and `sup` have been available in the `IntervalArithmetic.jl` package since `0.15`, which is the earliest version of `IntervalArithmetic.jl` our package supports: https://github.com/JuliaIntervals/IntervalArithmetic.jl/blob/e19764302e41c1b619b2a50727586be4ff90b6c7/src/IntervalArithmetic.jl#L55.
=> Change direct access of `.lo` and `.hi` fields to function calls to `inf` and `sup`.

.github/workflows/CI.yml, .prettierrc.yaml, CONTRIBUTING.md, README.md, docs/src/finding_adversarial_examples/batch_processing.md, docs/src/finding_adversarial_examples/single_image.md, docs/src/index.md, docs/src/net_components/core_ops.md, docs/src/net_components/layers.md, docs/src/net_components/nets.md, docs/src/net_components/overview.md, docs/src/tutorials.md, docs/src/utils/import_datasets.md, docs/src/utils/import_example_nets.md, docs/src/utils/import_weights.md
Reproducing:
```
$ npm install --save-dev --save-exact prettier
$ npx prettier . --write
```
In a subsequent PR, we will add a GitHub action to enforce that files are properly formatted.
=> Apply prettier tool to entire repo.

src/MIPVerify.jl, src/net_components/core_ops.jl
This PR is intended as a step in the right direction for #159. We may need to reinstate (optional) tolerances for users.
=> document behavior of find_adversarial_example in producing 'ties'

examples/00_quickstart.ipynb, examples/01_importing_your_own_neural_net.ipynb, examples/02_finding_adversarial_examples_in_depth.ipynb, examples/03_interpreting_the_output_of_find_adversarial_example.ipynb, examples/04_managing_log_output.ipynb
- Switch from Gurobi to HiGHS to enable repro without having a Gurobi license.
- Remove L2-norm example as HiGHS does not appear to support MIQP
=> Update example Jupyter notebooks.

examples/01_importing_your_own_neural_net.ipynb, src/utils/prep_data_file.jl
I manually uploaded the files currently at http://github.com/vtjeng/MIPVerify_data to the relevant GCP bucket.
This allows us to reduce spend on Git LFS and get more reliably behavior.
=> Move data source for MIPVerify_data.

src/MIPVerify.jl, test/integration/sequential.jl, test/integration/sequential/margin.jl
Fixes https://github.com/vtjeng/MIPVerify.jl/issues/160
=> Restore `margin` parameter in `find_adversarial_example`
